[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#e5e5e5"
yellow = "#f5f543"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#181818"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
# background = "#0e0e0e"
background = "#181818"
foreground = "#cccccc"

[colors.selection]
background = "#3a3d41"
text = "#e0e0e0"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Input Nerd Font"

[font.normal]
family = "Input Nerd Font"

[font.offset]
x = 0
y = -1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
decorations = "none"

[scrolling]
history = 100000
